name: create-issue

on:
  workflow_dispatch:
jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Get yesterday's date
        id: date
        run: |
          echo "::set-output name=yesterday::$(date  --date="yesterday" +"%Y-%m-%d")"   

      - name: Create an issue
        uses: actions-ecosystem/action-create-issue@v1
        with:
          github_token: ${{ secrets.github_token }}
          title:  EPA Submissions for ${{ steps.date.outputs.yesterday }}
          body: |
            * If any submissions, they will be here: https://github.com/conoro/epa-rss/blob/main/output/csv/daily/${{ steps.date.outputs.yesterday }}.csv 
