name: scrape-epa

on:
  workflow_dispatch:
  schedule:
    - cron: '17 1 * * *' # Run once a day at 1:17am
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner
      
      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
      - name: npm install, build, and run code
        run: |
          npm install
          cp sqlite/epa-rss-template.sqlite sqlite/epa-rss.sqlite
          npm run build
          npm run generate          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "update EPS data" -a
          git push
      - name: upload sqlite3 to s3
        uses: actions/checkout@master
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'sqlite'
      - name: Get yesterday's date
        id: date
        run: |
          echo "::set-output name=yesterday::$(date  --date="yesterday" +"%Y-%m-%d")"   
      - name: Create an issue
        uses: actions-ecosystem/action-create-issue@v1
        with:
          github_token: ${{ secrets.github_token }}
          title:  EPA Submissions for ${{ steps.date.outputs.yesterday }}
          body: |
            * If any submissions, they will be here: https://github.com/conoro/epa-rss/blob/main/output/csv/daily/${{ steps.date.outputs.yesterday }}.csv 
          labels: |
            closeme
      - name: Close those automatic issues
        uses: bdougie/close-issues-based-on-label@master
        env:
          LABEL: closeme
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
