name: Update Notification

on:
  push:
    branches: [ main ]
    paths:
      - 'output/csv/daily/**/*.csv'

jobs:
  create-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get current date
        id: date
        run: |
          echo "current_date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          echo "current_year=$(date +'%Y')" >> $GITHUB_OUTPUT
          echo "current_month=$(date +'%m')" >> $GITHUB_OUTPUT

      - name: Check if CSV exists for today
        id: check_csv
        run: |
          CSV_PATH="output/csv/daily/${{ steps.date.outputs.current_year }}/${{ steps.date.outputs.current_month }}/${{ steps.date.outputs.current_date }}.csv"
          if [ -f "$CSV_PATH" ]; then
            echo "csv_exists=true" >> $GITHUB_OUTPUT
            echo "csv_url=https://github.com/${{ github.repository }}/blob/main/$CSV_PATH" >> $GITHUB_OUTPUT
          else
            echo "csv_exists=false" >> $GITHUB_OUTPUT
            echo "csv_url=" >> $GITHUB_OUTPUT
          fi

      - name: Create notification issue
        run: |
          if [ "${{ steps.check_csv.outputs.csv_exists }}" = "true" ]; then
            echo "New EPA submissions have been added to the repository." > message.txt
            echo "" >> message.txt
            echo "**Download the latest CSV file:**" >> message.txt
            echo "[${{ steps.date.outputs.current_date }}.csv](${{ steps.check_csv.outputs.csv_url }})" >> message.txt
            echo "" >> message.txt
            echo "[View all CSV files](https://github.com/${{ github.repository }}/tree/main/output/csv/daily)" >> message.txt
          else
            echo "New EPA submissions have been processed, but no CSV file was generated for today (${{ steps.date.outputs.current_date }})." > message.txt
            echo "" >> message.txt
            echo "[View all CSV files](https://github.com/${{ github.repository }}/tree/main/output/csv/daily)" >> message.txt
          fi
          
          BODY=$(cat message.txt)
          rm message.txt
          
          gh issue create \
            --title "New EPA Submissions - ${{ steps.date.outputs.current_date }}" \
            --body "$BODY" \
            --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
