name: scrape-epa

on:
  workflow_dispatch:
  schedule:
    - cron: '7 5 * * *' # Run once a day at 5:07am
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner
      
      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
      - name: npm install, build, and test
        run: |
          npm install
          npm run build
          npm run experiment          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "update data" -a
